#!/usr/bin/env bash
# OpenWind setup — single command to a running system.
# Creates ../zitadel/ at runtime, pulls the official Zitadel image, generates a
# PAT, then runs the OpenWind bootstrap — all in one shot.
set -euo pipefail

OW_DIR="$(cd "$(dirname "$0")" && pwd)"
ZITA_DIR="$(dirname "$OW_DIR")/zitadel"
OUTPUT_DIR="$ZITA_DIR/output"
PAT_FILE="$OUTPUT_DIR/pat.txt"
GEN_PAT_SRC="$OW_DIR/scripts/gen-pat.mjs"

# ── Deployment config — override via environment for hosted deployments ────────
# Set these in .env.server (gitignored) and source it before running this script.
# Defaults produce the standard local dev setup (localhost, HTTP).
ZITADEL_EXTERNAL_DOMAIN="${ZITADEL_EXTERNAL_DOMAIN:-localhost}"
ZITADEL_HOST_PORT="${ZITADEL_HOST_PORT:-8080}"
ZITADEL_EXTERNALSECURE="${ZITADEL_EXTERNALSECURE:-false}"
# ZITADEL_EXTERNAL_PORT is the public port browsers use (443 for HTTPS behind a
# reverse proxy, same as ZITADEL_HOST_PORT for direct HTTP deployments).
ZITADEL_EXTERNAL_PORT="${ZITADEL_EXTERNAL_PORT:-${ZITADEL_HOST_PORT}}"
# tlsMode: "disabled" for local dev (no reverse proxy), "external" when nginx/caddy
# terminates TLS in front of Zitadel. Must be "external" for EXTERNALSECURE=true to work.
ZITADEL_TLS_MODE="${ZITADEL_TLS_MODE:-disabled}"

# Browser-accessible Zitadel URL — shown in summary and used in OIDC config
if [[ "$ZITADEL_EXTERNALSECURE" == "true" ]]; then
  ZITADEL_BROWSER_URL="https://${ZITADEL_EXTERNAL_DOMAIN}"
elif [[ "$ZITADEL_EXTERNAL_DOMAIN" != "localhost" ]]; then
  ZITADEL_BROWSER_URL="http://${ZITADEL_EXTERNAL_DOMAIN}:${ZITADEL_HOST_PORT}"
else
  ZITADEL_BROWSER_URL="http://localhost:${ZITADEL_HOST_PORT}"
fi

OPENWIND_URL="${APP_URL:-http://localhost:${ADMIN_UI_HOST_PORT:-3001}}"

# ── Colours ───────────────────────────────────────────────────────────────────
C='\033[0;36m'; G='\033[0;32m'; Y='\033[0;33m'; R='\033[0m'; DIM='\033[2m'
banner() { echo -e "\n  ${C}$1${R}"; }
ok()     { echo -e "  ${G}[+]${R} $1"; }
info()   { echo -e "  ${DIM}-->  $1${R}"; }
fail()   { echo -e "\n  ${Y}[!] $1${R}\n"; exit 1; }

echo ""
echo "  ============================================="
echo "   OpenWind Setup"
echo "  ============================================="
echo ""

# ── Step 1: Create ../zitadel/ if it doesn't exist ───────────────────────────
banner "Step 1/4  Setting up Zitadel identity provider"

if [[ ! -d "$ZITA_DIR" ]]; then
  mkdir -p "$OUTPUT_DIR"
  ok "Created $ZITA_DIR"
else
  info "Zitadel directory already exists — skipping creation"
fi

# Write docker-compose.yml for Zitadel
cat > "$ZITA_DIR/docker-compose.yml" <<COMPOSE
name: zitadel

# Auto-generated by OpenWind setup script — do not edit manually
# Source: $GEN_PAT_SRC
# Recreate by deleting this folder and re-running ./setup.sh in the OpenWind repo.

services:

  zitadel-db:
    container_name: zitadel-db
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: zitadel
      POSTGRES_PASSWORD: zitadel_dev_password
      POSTGRES_DB: zitadel
    volumes:
      - zitadel_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zitadel -d zitadel"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - internal

  zitadel:
    container_name: zitadel
    image: ghcr.io/zitadel/zitadel:v4.15.1
    restart: unless-stopped
    command: start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode ${ZITADEL_TLS_MODE}
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: zitadel-db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel_dev_password
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: zitadel_dev_password
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALSECURE: "${ZITADEL_EXTERNALSECURE}"
      ZITADEL_EXTERNALPORT: "${ZITADEL_EXTERNAL_PORT}"
      ZITADEL_EXTERNALDOMAIN: "${ZITADEL_EXTERNAL_DOMAIN}"
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: owZitadelAdmin@openwind.local
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: Admin1234!
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: "false"
      ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_FORCEMFA: "false"
      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED: "false"
      ZITADEL_DEFAULTINSTANCE_FEATURES_TOKENEXCHANGE: "true"
    ports:
      - "${ZITADEL_HOST_PORT}:8080"
    depends_on:
      zitadel-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/app/zitadel", "ready"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    networks:
      - internal
      - openwind_zitadel

  ow-zita-setup:
    container_name: ow-zita-setup
    profiles: [setup]
    image: node:22-alpine
    working_dir: /app
    volumes:
      - $GEN_PAT_SRC:/app/scripts/gen-pat.mjs:ro
      - $OUTPUT_DIR:/app/output
    command: node /app/scripts/gen-pat.mjs
    environment:
      ZITADEL_EXTERNALDOMAIN: "${ZITADEL_EXTERNAL_DOMAIN}"
      ZITADEL_EXTERNALSECURE: "${ZITADEL_EXTERNALSECURE}"
    networks:
      - openwind_zitadel
    depends_on:
      zitadel:
        condition: service_started
    restart: "no"

networks:
  internal:
    internal: true
  openwind_zitadel:
    name: openwind_zitadel

volumes:
  zitadel_db_data:
COMPOSE

ok "docker-compose.yml written to $ZITA_DIR"

# ── Step 2: Start Zitadel + generate PAT ────────────────────────────────────
banner "Step 2/4  Starting Zitadel and generating bootstrap PAT"
info "(First boot takes 60-90s while Zitadel initialises)"
echo ""

cd "$ZITA_DIR"

docker compose up -d || fail "Failed to start Zitadel containers"

# Remove stale PAT file from a previous run
[[ -f "$PAT_FILE" ]] && rm -f "$PAT_FILE"

docker compose --profile setup run --rm ow-zita-setup \
  || fail "PAT generation failed — check: docker compose logs zitadel"

cd "$OW_DIR"

[[ -f "$PAT_FILE" ]] || fail "PAT file not found at $PAT_FILE — gen-pat.mjs did not complete"
PAT="$(cat "$PAT_FILE" | tr -d '[:space:]')"
[[ -n "$PAT" ]] || fail "PAT file is empty"

# Remove PAT file immediately
rm -f "$PAT_FILE"
ok "PAT received (in memory — not stored on disk)"
echo ""

# ── Step 3: Run OpenWind bootstrap ──────────────────────────────────────────
banner "Step 3/4  Running OpenWind bootstrap"
info "(Migrations, seed data, Zitadel OIDC config, demo users)"
echo ""

if [[ ! -f ".env.local" ]]; then
  [[ -f ".env.example" ]] && cp ".env.example" ".env.local" || touch ".env.local"
fi

docker compose up -d postgres pgbouncer redis \
  || fail "Failed to start infrastructure containers"

docker compose --profile bootstrap run --build -e "ZITADEL_SETUP_PAT=${PAT}" --rm bootstrap \
  || fail "Bootstrap failed — check the output above"

# Clear PAT — bootstrap has converted it to key JSON in .env.local
PAT=""

# ── Step 4: Start app containers ─────────────────────────────────────────────
banner "Step 4/4  Starting app containers"

docker compose up -d --force-recreate ow-backend ow-frontend \
  || { echo "  [!] Could not start app containers. Run: docker compose up -d ow-backend ow-frontend"; }

ok "App containers started"

echo ""
echo "  ============================================="
echo "   Done!"
echo ""
echo "   OpenWind:  $OPENWIND_URL"
echo "   Zitadel:   $ZITADEL_BROWSER_URL"
echo "  ============================================="
echo ""
echo "   owAdmin / OpenWind1234!   (admin)"
echo "   owUser  / OpenWind1234!   (user)"
echo ""
